### ISSUE TITLE
Error when loading keymap

### ISSUE THREAD

**Issue by Linuus** [CJNE/vikeys#9]
Hi

I really like the configurator you have built. It looks awesome!

I tried to create a new keymap from scratch, added one layer only and saved. Now when I try to load it vikeys seems to crash with this message:

```
TypeError: Cannot read property 'length' of null
    at /usr/local/lib/node_modules/vikeys/firmwares/tmk.js:372:30
    at fs.js:271:14
    at Object.oncomplete (fs.js:107:15)
```

My keymap_linus.h file looks like this: https://gist.github.com/Linuus/f0557f04c69265575568

Any ideas on how to fix it?

**Comment by Linuus** [comment]
The issue seems to be that I haven't created any actions.

**Comment by CJNE** [comment]
NIce catch, yeah it should be an easy fix, thanks!

**Comment by CJNE** [comment]
Fixed, than you Linuus!
